# Generated by Django 4.1 on 2025-04-26 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plazoleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSociales',
            fields=[
                ('IdOS', models.AutoField(primary_key=True, serialize=False)),
                ('NombreOS', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('IdSucursal', models.AutoField(primary_key=True, serialize=False)),
                ('NombreSuc', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('IdTarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTarjeta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('IdCaja', models.AutoField(primary_key=True, serialize=False)),
                ('FechaHora', models.DateTimeField()),
                ('SaldoInicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ImporteVentas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ImporteEfectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ImporteTarjetas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ImporteParticulares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ImporteOSociales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HoraInicio', models.TimeField(blank=True, null=True)),
                ('HoraCierre', models.TimeField(blank=True, null=True)),
                ('Operaciones', models.IntegerField(default=0)),
                ('Efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Tarjetas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Particulares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('OSociales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('IdSucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plazoleta.sucursal')),
            ],
        ),
    ]
