# Generated by Django 5.2 on 2025-05-01 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazoleta', '0004_alter_usuario_groups_alter_usuario_grupodeacceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_caja', to=settings.AUTH_USER_MODEL, verbose_name='Cajero'),
        ),
    ]
