# Generated by Django 5.2 on 2025-05-03 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazoleta', '0005_caja_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCaja',
            fields=[
                ('IdHistorialCaja', models.AutoField(primary_key=True, serialize=False)),
                ('FechaHoraMovimiento', models.DateTimeField(auto_now_add=True)),
                ('TipoMovimiento', models.CharField(choices=[('ALTA', 'Alta'), ('MODIFICACION', 'Modificación'), ('BAJA', 'Baja')], max_length=20)),
                ('SaldoInicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ImporteVentas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ImporteEfectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ImporteTarjetas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ImporteParticulares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ImporteOSociales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('HoraInicio', models.TimeField(blank=True, null=True)),
                ('HoraCierre', models.TimeField(blank=True, null=True)),
                ('Operaciones', models.IntegerField(blank=True, default=0, null=True)),
                ('Efectivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('Tarjetas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('Particulares', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('OSociales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('IdCaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plazoleta.caja')),
                ('Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cajas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
