# Generated by Django 5.2 on 2025-05-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazoleta', '0007_alter_historialcaja_idcaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcaja',
            name='IdSucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cajas', to='plazoleta.sucursal'),
        ),
    ]
