# Generated by Django 5.2 on 2025-05-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazoleta', '0008_historialcaja_idsucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='fec_mov',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historialcaja',
            name='fec_mov',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialcaja',
            name='FechaHoraMovimiento',
            field=models.DateTimeField(),
        ),
    ]
