# Generated by Django 5.2 on 2025-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plazoleta', '0009_caja_fec_mov_historialcaja_fec_mov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcaja',
            name='caja_id_historico',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Caja Histórico'),
        ),
        migrations.AddField(
            model_name='historialcaja',
            name='fecha_caja_historico',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Caja Histórico'),
        ),
        migrations.AddField(
            model_name='historialcaja',
            name='nombre_sucursal_historico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Sucursal Histórico'),
        ),
        migrations.AddField(
            model_name='historialcaja',
            name='sucursal_id_historico',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Sucursal Histórico'),
        ),
    ]
